import type { Match, RankingItem } from './types';

export const mockMatches: Match[] = [
  {
    id: 'argentina-mexico',
    home: 'Argentina',
    away: 'Mexico',
    homeFlag: 'ARG',
    awayFlag: 'MEX',
    date: '15 JUN 2026',
    time: '18:00',
    stadium: 'Estadio Azteca',
    group: 'Grupo A',
    winnerStake: 1,
    exactScoreStake: 2,
  },
  {
    id: 'brasil-francia',
    home: 'Brasil',
    away: 'Francia',
    homeFlag: 'BRA',
    awayFlag: 'FRA',
    date: '20 JUN 2026',
    time: '16:00',
    stadium: 'Estadio Lusail',
    group: 'Grupo B',
    winnerStake: 1,
    exactScoreStake: 2,
  },
  {
    id: 'portugal-alemania',
    home: 'Portugal',
    away: 'Alemania',
    homeFlag: 'POR',
    awayFlag: 'GER',
    date: 'EN VIVO',
    time: '65:23',
    stadium: 'Arena Internacional',
    group: 'Partido en vivo',
    winnerStake: 1,
    exactScoreStake: 2,
    live: true,
    score: '1 - 1',
  },
  {
    id: 'espana-italia',
    home: 'Espana',
    away: 'Italia',
    homeFlag: 'ESP',
    awayFlag: 'ITA',
    date: '22 JUN 2026',
    time: '19:30',
    stadium: 'MetLife Stadium',
    group: 'Grupo C',
    winnerStake: 1,
    exactScoreStake: 2,
  },
  {
    id: 'uruguay-eeuu',
    home: 'Uruguay',
    away: 'Estados Unidos',
    homeFlag: 'URU',
    awayFlag: 'USA',
    date: '24 JUN 2026',
    time: '20:00',
    stadium: 'SoFi Stadium',
    group: 'Grupo D',
    winnerStake: 1,
    exactScoreStake: 2,
  },
];

export const mockRankings: RankingItem[] = [
  { position: 1, name: 'Carlos Ramirez', totalStaked: 56, predictionsCount: 9, medal: '1' },
  { position: 2, name: 'Maria Lopez', totalStaked: 52, predictionsCount: 8, medal: '2' },
  { position: 3, name: 'Juan Perez', totalStaked: 45, predictionsCount: 7, medal: '3' },
  { position: 4, name: 'Pedro Sanchez', totalStaked: 20, predictionsCount: 4, medal: '4' },
  { position: 5, name: 'Ana Torres', totalStaked: 12, predictionsCount: 3, medal: '5' },
];
