import type { Match, RankingItem } from './types';

export const mockMatches: Match[] = [
  {
    id: 'argentina-mexico',
    home: 'Argentina',
    away: 'Mexico',
    homeFlag: 'ARG',
    awayFlag: 'MEX',
    date: '15 JUN 2026',
    time: '18:00',
    stadium: 'Estadio Azteca',
    group: 'Grupo A',
    winnerStake: 1,
    exactScoreStake: 2,
  },
  {
    id: 'brasil-francia',
    home: 'Brasil',
    away: 'Francia',
    homeFlag: 'BRA',
    awayFlag: 'FRA',
    date: '20 JUN 2026',
    time: '16:00',
    stadium: 'Estadio Lusail',
    group: 'Grupo B',
    winnerStake: 1,
    exactScoreStake: 2,
  },
  {
    id: 'portugal-alemania',
    home: 'Portugal',
    away: 'Alemania',
    homeFlag: 'POR',
    awayFlag: 'GER',
    date: 'EN VIVO',
    time: '65:23',
    stadium: 'Arena Internacional',
    group: 'Partido en vivo',
    winnerStake: 1,
    exactScoreStake: 2,
    live: true,
    score: '1 - 1',
  },
  {
    id: 'espana-italia',
    home: 'Espana',
    away: 'Italia',
    homeFlag: 'ESP',
    awayFlag: 'ITA',
    date: '22 JUN 2026',
    time: '19:30',
    stadium: 'MetLife Stadium',
    group: 'Grupo C',
    winnerStake: 1,
    exactScoreStake: 2,
  },
  {
    id: 'uruguay-eeuu',
    home: 'Uruguay',
    away: 'Estados Unidos',
    homeFlag: 'URU',
    awayFlag: 'USA',
    date: '24 JUN 2026',
    time: '20:00',
    stadium: 'SoFi Stadium',
    group: 'Grupo D',
    winnerStake: 1,
    exactScoreStake: 2,
  },
];

export const mockRankings: RankingItem[] = [
  {
    position: 1,
    name: 'Carlos Ramirez',
    totalWon: 56,
    totalStaked: 18,
    balance: 38,
    predictionsCount: 9,
    winnerHits: 6,
    exactHits: 2,
    medal: '1',
  },
  {
    position: 2,
    name: 'Maria Lopez',
    totalWon: 52,
    totalStaked: 16,
    balance: 36,
    predictionsCount: 8,
    winnerHits: 5,
    exactHits: 2,
    medal: '2',
  },
  {
    position: 3,
    name: 'Juan Perez',
    totalWon: 45,
    totalStaked: 15,
    balance: 30,
    predictionsCount: 7,
    winnerHits: 4,
    exactHits: 2,
    medal: '3',
  },
  {
    position: 4,
    name: 'Pedro Sanchez',
    totalWon: 20,
    totalStaked: 8,
    balance: 12,
    predictionsCount: 4,
    winnerHits: 2,
    exactHits: 0,
    medal: '4',
  },
  {
    position: 5,
    name: 'Ana Torres',
    totalWon: 12,
    totalStaked: 6,
    balance: 6,
    predictionsCount: 3,
    winnerHits: 1,
    exactHits: 0,
    medal: '5',
  },
];
